# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fluent-plugin-couchbase"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["atWare, Inc."]
  s.date = "2015-10-22"
  s.description = "Fluent output plugin for Couchbase 2.0"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/fluent/plugin/out_couchbase.rb",
    "spec/out_couchbase_spec.rb"
  ]
  s.homepage = "https://github.com/atware/fluent-plugin-couchbase"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Fluent output plugin for Couchbase 2.0"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    s.add_runtime_dependency(%q<fluentd>, [">= 0.10.50"])
    s.add_runtime_dependency(%q<couchbase>, [">= 0"])
    s.add_development_dependency(%q<rspec>, [">= 0"])
    s.add_development_dependency(%q<rspec-core>, [">= 0"])
    s.add_development_dependency(%q<activesupport>, [">= 0"])
    s.add_development_dependency(%q<rake>, [">= 0"])
    s.add_development_dependency(%q<minitest>, ["~> 4.0"])
    s.add_development_dependency(%q<simplecov>, [">= 0"])
  end
end

